### ISSUE TITLE
bpfc treats programs with uninitialized reads as valid

### ISSUE THREAD

**Issue by bhickey** [netsniff-ng/netsniff-ng#121] opened 2014-04-25 13:49 UTC
bpfc compiles and validates the following program:
````
ld  M[0]
ret #0
````
````
2,96 0 0 0,6 0 0 0,
````
However, this is then rejected inside the kernel for containing an uninitialized read. While this example is contrived, this sort of error is easy to make with conditional branches.

With the addition of a store instruction, it behaves as expected.
````
st  M[0]
ld  M[0]
ret #0
````
````
3,2 0 0 0,96 0 0 0,6 0 0 0,
````

Finally, it isn't entirely clear to me that the validator in the kernel is behaving correctly -- the BPF vm should begin with its state zeroed out.

**Comment by borkmann** [comment] 2015-04-21 11:06
Hi Brandon, I would close this for now. The actual verifier resides in kernel space, and as mentioned checks if the scratch mem store is actually initialized before any reads are being done. The reason why this has been done like this is, as mentioned, so that we do not need to memset() the scratch store for ever incoming skb when the filter is invoked. bpfc was designed also for the purpose of debugging the kernel verifier, so it does only very primitive checks, and simple sanity checking can also be disabled entirely. For debuggability, the kernel has a small helper tool, that is bpf_dbg, that is available under tools/net/ (http://lingrok.org/xref/linux-net-next/tools/net/bpf_dbg.c), but I presume you've seen this already. Thanks for reporting!

**Closed by borkmann** 2015-04-21 11:06 UTC

**Comment by bhickey** [comment] 2015-04-26 13:08
Thanks for the reply, Daniel.
Yes, I've seen bpf_dbg. I patched it last April :)
