### ISSUE TITLE
curvetun: Runtime Crash (Illegal Operation)

### ISSUE THREAD

**Issue by heri16** [netsniff-ng/netsniff-ng#116] opened 2014-04-14 08:01 UTC
On RHEL 6.5, curvetun crashes during key generation (curvetun -k).

I used "make DISTRO=1" to work around this problem.

Can someone check what is wrong with the standard build process?

**Comment by vkochan** [comment] 2015-11-09 09:31
I checked on the latest master:
# uname -a
Linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

and it succeeded:

~/src/netsniff-ng$ curvetun/curvetun -k
curvetun directory /home/$(USER)/.curvetun/ created!
Empty client file written to /home/$(USER)/.curvetun/clients!
Empty server file written to /home/$(USER)/.curvetun/servers!
Username: [$(USER)] ls ~/.curv* 
Username written to /home/$(USER)/.curvetun/username!
Reading from /dev/random (this may take a while) ...
Public key written to /home/$(USER)/.curvetun/pub.key!

**Comment by tklauser** [comment] 2017-06-20 08:58
Cannot reproduce this either. Will thus close the issue but feel free to reopen (with build logs, netsniff-ng version you're using and curvetun output log) if this still is an issue for you.

**Closed by tklauser** 2017-06-20 08:58 UTC
