### ISSUE TITLE
Cannot use mergecap on netsniff-ng --out pcap files

### ISSUE THREAD

**Issue by zachsis** [netsniff-ng/netsniff-ng#157] opened 2016-05-03 18:47 UTC
It appears that when writing a pcap file output, it is not the correct format for mergecap to use. I am doing a for loop to read multiple pcap files in, find packets matching my BPF, and then write the output to a new file--which i then would like to combine all of the pcaps at the end with mergecap.

```
#!/bin/bash
...
...
for i in $(ls /var/packet_recorder/ | grep "${GREPFILTER}"); do 
  /bin/taskset -c 30 netsniff-ng --in /var/packet_recorder/"${i}" --filter "${BPFFILTER}" --out /var/packet_recorder/temp/"${DATESTAMP}"/"${i}"
done
```

```

# mergecap * -w merged.pcap
mergecap: Can't open InternetBorder.2016-05-03_09:00:37.pcap: The file isn't a capture file in a known format

```
```

# file *
InternetBorder.2016-05-03_09:00:37.pcap: ASCII text
InternetBorder.2016-05-03_09:01:34.pcap: ASCII text
InternetBorder.2016-05-03_09:02:02.pcap: ASCII text

```

**Comment by vkochan** [comment] 2016-05-16 07:12
Hi,

The problem is that output pcap file is created with pcap header before packet filtering. I really have a fix for this which creates the pcap file only after at least 1 packet passes, but really mergecap should consider such *empty* pcap's ?

Also the funny thing is that netsniff-ng was not able to open my merged.pcap:

    $ sudo netsniff-ng/netsniff-ng -i /tmp/merged.pcap 
    This file has not a valid pcap header

So I'd like to have some comments from Daniel or Tobias, before sending the *fix*.

Regards,
Vadim Kochan

**Comment by vkochan** [comment] 2016-05-16 07:36
OK, seems mergecap merges input files into pcap-ng format by default. Anyway this is not related to
the issue, just some investigation.

**Comment by vkochan** [comment] 2016-07-13 10:00
From Tobias:
------------------->8-------------------------------
IMO, an output file should always be created, even if it contains no
packets. Otherwise it's not entirely obvious whether there was an error
in netsniff-ng or whether there just weren't any passed packets. Also,
in case the file can't be created (e.g. due to lacking permissions) and
the first packet to be written only arrives a large amount of time after
program start, the user would only notice by then.

BTW, an empty pcap opens just fine in e.g. Wireshark.
------------------>8---------------------------------

So it looks like this issue might be closed ?

**Comment by tklauser** [comment] 2016-07-13 11:49
Yes, if this is really a case of mergecap not handling empty pcap files properly. Not sure though whether this is really what originally caused @zachsis' issue (the `file` output makes me a bit suspicious as it shows `ASCII text`, which it doesn't for me with an empty pcap).

In any case, I'll close this issue for now. @zachsis, if you think the problem still exists and is caused by netsniff-ng, could you please reopen the issue and provide an example `InternetBorder.*.pcap` file?

**Closed by tklauser** 2016-07-13 11:49 UTC
